#!/bin/bash

# KeePass
sudo apt-add-repository -y ppa:jtaylor/keepass
#sudo apt-get update
sudo apt-get -y install keepass2
sudo apt-get -y install software-properties-common ca-certificates lsb-release apt-transport-https gnupg
sudo apt-get -y install autoconf gcc libc6-dev build-essential net-tools
sudo apt-get -y install php php-pear
sudo apt-get -y install php-mbstring php-zip php-xml php-mysql php-gd php-imagick
sudo apt-get -y install php-mongodb php-cli php-redis php-bz2
sudo apt-get -y install apache2 phpmyadmin
sudo apt-get -y install mariadb-server mariadb-client mariadb-common
sudo apt-get -y install git curl tomboy-ng gimp ripgrep openvpn guake yarn composer git-cola tig ranger dmenu rofi fzf moreutils flameshot deluge
sudo apt-get -y install scrot mencoder # For screen timelapse creation in ~/screencasts
sudo apt-get -y install ffmpeg mkvtoolnix meld vlc xdotool pipx

pipx install rofimoji

# Install NerdFonts patched fonts, including favorite CodeNewRoman
mkdir -p ${HOME}/fonts/NerdFonts
cd ${HOME}/fonts/NerdFonts
# Code New Roman:
if [[ ! -f "Code New Roman Nerd Font Complete.otf" ]] then
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CodeNewRoman/Regular/complete/Code%20New%20Roman%20Nerd%20Font%20Complete.otf
fi
if [[ ! -f "Code New Roman Nerd Font Complete Mono.otf" ]] then
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CodeNewRoman/Regular/complete/Code%20New%20Roman%20Nerd%20Font%20Complete%20Mono.otf
fi
if [[ ! -f "Code New Roman Bold Nerd Font Complete.otf" ]] then
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CodeNewRoman/Bold/complete/Code%20New%20Roman%20Bold%20Nerd%20Font%20Complete.otf
fi
if [[ ! -f "Code New Roman Bold Nerd Font Complete Mono.otf" ]] then
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CodeNewRoman/Bold/complete/Code%20New%20Roman%20Bold%20Nerd%20Font%20Complete%20Mono.otf
fi
if [[ ! -f "Code New Roman Italic Nerd Font Complete.otf" ]] then
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CodeNewRoman/Italic/complete/Code%20New%20Roman%20Italic%20Nerd%20Font%20Complete.otf
fi
if [[ ! -f "Code New Roman Italic Nerd Font Complete Mono.otf" ]] then
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/CodeNewRoman/Italic/complete/Code%20New%20Roman%20Italic%20Nerd%20Font%20Complete%20Mono.otf
fi
# Ubuntu Mono:
if [[ ! -f "Ubuntu Mono Nerd Font Complete.ttf" ]] then
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/Regular/complete/Ubuntu%20Mono%20Nerd%20Font%20Complete.ttf
fi
if [[ ! -f "Ubuntu Mono Italic Nerd Font Complete.ttf" ]] then
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/Regular-Italic/complete/Ubuntu%20Mono%20Italic%20Nerd%20Font%20Complete.ttf
fi
if [[ ! -f "Ubuntu Mono Bold Nerd Font Complete.ttf" ]] then
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/Bold/complete/Ubuntu%20Mono%20Bold%20Nerd%20Font%20Complete.ttf
fi
if [[ ! -f "Ubuntu Mono Bold Italic Nerd Font Complete.ttf" ]] then
wget https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/UbuntuMono/Bold-Italic/complete/Ubuntu%20Mono%20Bold%20Italic%20Nerd%20Font%20Complete.ttf
fi


#Vim plugins
vim -c "PlugInstall" -c "qa"
